#!/usr/bin/env python3
import random
import skilstak.colors as c
import time
def play(level):
    checkfor = ''
    print(c.cl)
    alphabet = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    for count in range(level):
        number = random.choice(numbers)
        print(number,'  '+alphabet[count])
        if level <= 6:
            time.sleep(0.5)
        else:
            time.sleep(0.7)
        print(c.cl)
        checkfor += str(number)
    return checkfor
if __name__ == '__main__':
    numbers = [1,2,3,4]
    level = 1
    print("do not type the letters. they are there for reference")
    x = input("press enter to start")
    while True:
        checkfor = play(level)
        userinput = input(" > ")
        if userinput == checkfor:
            level += 1
            print('level', level)
        else:
            print("You lost at round ",level)
            print(checkfor)
            print(userinput)
            break

