#!/usr/bin/env python3
grid = [[" ","1","2","3"],["a"," "," "," "],["b"," "," "," "],["c"," "," "," "]]
for row in grid:
    myrow = ""
    for item in row:
        myrow += item + " "
    print(myrow)
line = input('where would you like to go?')
place = list(line)
print(place)
print(grid[0][int(place[1])])

