#!/usr/bin/env python3
import skilstak.colors as c
import random
answers = ["0000","0001","0010","0011","0100","0101","0110","0111","1000","1001","1010","1011","1100","1101","1110","1111"]
try:
    while True:
        pick = random.choice(answers)                                                                                                                                   
        a = random.choice(answers)                                                                                                                                      
        b = random.choice(answers)                                                                                                                                      
        c = random.choice(answers)                                                                                                                                      
        d = random.choice(answers)                                                                                                                                      
        e = random.choice(answers)                                                                                                                                      
        f = random.choice(answers)                                                                                                                                      
        g = random.choice(answers)                                                                                                                                      
        h = random.choice(answers)                                                                                                                                      
        i = random.choice(answers)                                                                                                                                      
        j = random.choice(answers)                                                                                                                                      
        k = random.choice(answers)                                                                                                                                      
        l = random.choice(answers)                                                                                                                                      
        m = random.choice(answers)                                                                                                                                      
        n = random.choice(answers)                                                                                                                                      
        o = random.choice(answers)                                                                                                                                      
        p = random.choice(answers)
        print(pick + " " + a + " " + b  + " " + c + " " + d + " " + e + " " + f + " " + g + " " + h + " " + i + " " + j + " " + k  + " " + l + " " + m + " " + n + " " + o + " " + p + " " + pick + " " + a + " " + b + " " + c + " " + d + " " + e + " " + f + " " + g + " " + h + " " + i + " " + j + " " + k + " " + l, end = " ")
except KeyboardInterrupt:
    print(c.clear + c.rc() + "hacking complete:}")
    exit()

