#!/usr/bin/env python3
import skilstak.colors as co
for c in range(7):
    for x in range(3):
        print('(({},{}),({},{}),({},{}),({},{}))'.format(c,x,c,x+1,c,x+2,c,x+3))
for r in range(6):
    for c in range(4):
        print('(({},{}),({},{}),({},{}),({},{}))'.format(c,r,c+1,r,c+2,r,c+3,r))
for c in range(3):
    for r in range(4):
        print('(({},{}),({},{}),({},{}),({},{}))'.format(c,r,c+1,r+1,c+2,r+2,c+3,r+3))
        print('(({},{}),({},{}),({},{}),({},{}))'.format(c,r+3,c+1,r+2,c+2,r+1,c+3,r))
