#!/usr/bin/env python3
if __name__ == '__main__':
    import skilstak.colors as c
    import time as t
    try:
        x = 0
        while True:
            y = int(x + 1)
            z = str(y)
            print(c.multi(z))
            x = y
            t.sleep(1)
    except KeyboardInterrupt:
        exit()
