#!/usr/bin/env python3

from __future__ import print_function


import atexit
from os import path
from json import dumps, loads


def read_counter():
    return loads(open("counter.json", "r").read()) + 1 if path.exists("counter.json") else 0


def write_counter():
    with open("counter.json", "w") as f:
        f.write(dumps(counter))


counter = read_counter()
atexit.register(write_counter)


def main():
    print("I have been run {} times".format(counter))


if __name__ == "__main__":
    """the program is getting data from a .json file, reading it, adding one to the number in it, and writing the new integer to the .json file"""
    main()
