#!/usr/bin/env python3
import curses
import curses.panel

x = 3
y = 3
stdscr = curses.initscr()


w = curses.newwin(1, 20, y, x)
p = curses.panel.new_panel(w)
w.addstr(0, 0, "Hello World")
w.getch()
p.move(y+1, x)
curses.panel.update_panels()
curses.doupdate()
w.getch()

curses.endwin()

