#!/usr/bin/env python3
def use(x):
    addOne = x + 1
    square = x * x
    subtractOne = x -1
    multiplyVar = addOne * subtractOne
    return {'add':addOne, 'subtract':subtractOne,'square':square,'var':multiplyVar}
def find(toCall,function):
    toPrint = function[str(addQ)]
    print(toPrint)
if __name__ == '__main__':
    x = 5
    z = use(x)['add']
    '''in the function use(x), find the key in the dictionary'''
    print(z)
    subtract = 'subtract'
    a = use(x)[subtract]
    print(a)
    '''assign a variable to the quoted version, so you don't need quotes'''
    square = use(x)['square']
    print(square)
    '''remove the use(x) entirely'''
    function = use(x)
    toCall = 'var'[1:-1]
    find(toCall,function)
