#!/usr/bin/env python3
import skilstak.colors as c
import random
print(c.clear + c.green + "welcome to the random number generator")
print(c.blue + "how many digits do you want it to be?")
def ask(prompt):
    A = input(prompt + c.random()).strip().lower()
    return A 
def bye():
    print("goodbye")
    exit()
while True:
    A = ask("> ")
    if A == "1":
        for number in range(1,10):
            print(number)
            
        
        
