#!/usr/bin/env python3
if __name__ == "__main__":
  from os import system
  website = input("> ")
  'browser is w3m'
  'Q  to exit | B to go back'
  system('python -m webbrowser -t "{}"'.format(website))
