#!/usr/bin/env python3
import skilstak.colors as c
import random
print(c.clear + c.blue + 'Welcome to the Magic 8 Ball!')
print(c.rc() + 'Enter your question please.')
answers = ["I Think so","I think not","I am not sure-ask again",'Your face!',"Never","One second-I'm barfing","When pig's fly","Of course","When 4 Cubed isn't 64","Yes","No","ARE U CRAZY?"]

def ask(prompt):
    A = input(prompt + c.random()).strip().lower()    
    return A 

def bye():
    print("goodbye")
    exit()

while True:
    A = ask("> ")
    plip = random.choice(answers)
    if A == "what is the meaning of life?":
        print('42')
    elif "death" in A:
        f = open('skull.txt','r')
        file_contents = f.read()
        print(file_contents)
        f.close()
    elif "love" in A:
        print(c.red + 'love is beyond my powers to predict' + c.clear)
    elif "bye" in A or "goodbye" in A or "exit" in A:
        bye()
    elif A == "1+1":
        print('window,of course.')
    elif A == "2+2":
        print('Fish')
    elif A == "help":
        print('Control+C to Exit')
    elif "marry" in A:
        print('uhhhhhhhhhhhhhhhhhhhhhhhhhhh')
    else:
        print(plip)







