#!/usr/bin/env python3
import requests
import bs4
r = requests.get("http://edition.cnn.com/mostpopular/")

data = BeautifulSoup(r.content).find("div",{"id":"cnnMostPopularTabs1"}).find_all("div",{"class":"cnnMPContentHeadline"})

from pprint import pprint as pp
pp([d.a["href"] for d in data])

