#!/usr/bin/env python3
if __name__ == '__main__':
    import skilstak.colors as c
    import time as t
    try:
        x = 0
        print("control + c to stop - times in accuracy of 0.01")
        while True:
            y = float(x + .01)
            w = round(y,2)
            z = str(w)
            x = y
            t.sleep(.01)
    except KeyboardInterrupt:
        print(c.rc() + "Your time is "+ z + " seconds." + c.x)
        exit()
