#!/usr/bin/env python3
if __name__ == '__main__':
    import skilstak.colors as c
    import time as t
    try:
        x = 0
        while True:
            y = float(x + .1)
            w = round(y,1)
            z = str(w)
            print(c.multi(z))
            x = y
            t.sleep(.1)
    except KeyboardInterrupt:
        print(c.rc() + "Your time is "+ z + " seconds." + c.x)
        exit()
