#!/usr/bin/env python3
y = 0
z = 0
startmoney = 0
endmoney = 0
######VALUES########
goals = 1  # 1(ON) / 0(OFF)
goal = 1000000
money = 5000
commisonPerTrans = 6.99
taxPercent = .28
tradesPerYear = 2
gainPercent = .07
####################
if goals == 0:
    trades = int(input("# of trades:"))
    while z <= trades:
        startmoney = money
        print(z , ":", round(money,2))
        money = money * (1 + gainPercent) - (2*commisonPerTrans)
        y += 1
        z += 1
        if y == tradesPerYear:
            endmoney = money
            y = 0
            money = ((1-taxPercent)*(endmoney-startmoney))+startmoney
elif goals == 1:
    while money <= goal:
        startmoney = money
        print(z , ":", round(money,2))
        money = money * (1 + gainPercent) - (2*commisonPerTrans)
        y += 1
        z += 1
        if y == tradesPerYear:
            endmoney = money
            y = 0
            money = ((1-taxPercent)*(endmoney-startmoney))+startmoney
    print(z, ":", round(money,2))
