#!/usr/bin/env python3
y = 0
goals = True
goal = 1000000
money = 350
commisonPerTrans = 6.99
taxPercent = 0
percent = .50
if goals != True:
    trades = int(input("# of trades:"))
    while y <= trades:
        print(y , ":", money)
        money = (1-taxPercent)*(money * (1 + percent)) - (2*commisonPerTrans)
        y += 1
else:
    while money <= goal:
        print(y , ":", money)
        money = (1-taxPercent)*(money * (1 + percent)) - (2*commisonPerTrans)
        y += 1
    print(y, ":", money)
