#!/usr/bin/env python3
import time
from selenium import webdriver
try:
    driver = webdriver.Chrome()
    number = "0"
    while True:
        driver.get("http://nc.milesplit.com/articles/219526-vote-week-1-athlete-and-team-of-the-week-polls-")
        time.sleep(1)
        driver.find_element_by_id("PDI_answer44931799").click() #alexis
        driver.find_element_by_id("pd-vote-button9818444").click() #vote
        time.sleep(1)
        while True:
            try:
                new_number = driver.find_elements_by_css_selector(".pds-feedback-label")[0].text.split('\n')[1].split("  ")[1][1:-7]
                if new_number == number:
                    print("maxed")
                    driver.quit()
                    exit()
                print(new_number)
                number = new_number
                break
            except Exception:
                time.sleep(1)
except KeyboardInterrupt:
    driver.quit()
