#!/usr/bin/env python3
import time
from selenium import webdriver
try:
    driver = webdriver.Chrome()
    votes = int(input("how many sets of 25? > "))
    number = "0"
    for vote_set in range(votes):
        for count in range(25):
            driver.get("http://nc.milesplit.com/articles/219526-vote-week-1-athlete-and-team-of-the-week-polls-")
            time.sleep(1)
            driver.find_element_by_id("PDI_answer44931799").click() #alexis
            driver.find_element_by_id("pd-vote-button9818444").click() #vote
            time.sleep(1)
            while True:
                try:
                    new_number = driver.find_elements_by_css_selector(".pds-feedback-label")[0].text.split('\n')[1].split("  ")[1][1:-7]
                    print(new_number)
                    if new_number == number:
                        print("maxed")
                    number = new_number
                    break
                except Exception:
                    time.sleep(1)
        print("set #{}".format(vote_set+1))
        driver.quit()
        driver = webdriver.Chrome()
    driver.quit()
except KeyboardInterrupt:
    driver.quit()
