#!/usr/bin/env python3
print("""
s = sin 
c = cos
t = ta            /|
                 / |
hypotenuse >>>  /  | <<< opposite
               /   |
              /____|        
                adjacent

sin = opposite / hypotenuse
cos = adjacent / hypotenuse
tan = opposite / adjacent
        """)
q = input("s,c,t? > ")

if q == "s":
    q = input("angle of sin > ")
    x = int(q)
    w = input("opposite > ")
    y = int(w)
    u = input("hypotenuse > ")
    z = int(u)
    a = int
    a = 1.* y / z
    print("sin(",x,")=",a)
if q == "c":
    q = int(input("angle of cos > "))
    w = int(input("adj. > "))
    u = int(input("hypotenuse > "))
    a = int
    a = 1.* w / u
    print("cos(",x,")=",a)
if q == "t":
    q = int(input("angle of tan > "))
    w = int(input("opposite > "))
    u = int(input("adj. > "))
    a = int
    a = 1.* w / u
    print("sin(",x,")=",a)
else:
    exit()
