#!/usr/bin/env python3
for c in range(100000):
    if c % 2 == 0 and c % 5 == 0 and c % 7 == 0 and c % 9 == 0 and c % 11 == 0:
        if "9" in str(c) and "6" not in str(c):
            print(c)
        else:
            print('NOT VALID:{}'.format(c))
