#!/usr/bin/env python3
import math
def round_down(num, divisor):
    return num - (num%divisor)

print('''format:
4x^2_R4_5x^4_3y
_ = different expression
_4_ = radical sign, 4 is the index.
''')
raw = input('your top equation > ')
raw_split = raw.split('_R')
before_expressions = raw_split[0].split('_')
after_rad_split = raw_split[1].split('_')
index = int(after_rad_split[0])
after_expressions = after_rad_split[1:]
#simplify top form
for x in range(len(after_expressions)):
    expression = after_expressions[x]
    if '^' in expression:
        power_split = expression.split('^')
        
        power = int(power_split[1])
        div_power_index = math.floor(power/index)
        if div_power_index >= 1:
            power_split[1] = str(power - (div_power_index * index))
            new_rad = power_split[0] + '^' + str(div_power_index)
            if div_power_index == 1:
                before_expressions.append(power_split[0])
            else:
                before_expressions.append(new_rad)
        power_split.insert(1,'^')
        expression = ''.join(power_split)
        if '^1' in expression:
            expression = expression.split('^')[0]
    after_expressions[x] = expression

#remove ^0
after_expressions = [ x for x in after_expressions if "^0" not in x ]
print(before_expressions,index,after_expressions)
to_multiply = []
for expr in after_expressions:
    if '^' in expr:
        power = int(expr.split('^')[1])
        #if power is 8, index is 3, change index to 9   
