#!/usr/bin/env python3
'''finds the eqaution based on 3 points - quadratic regression'''
import sys
def printmainfunc(word,a,b,y):
    print(word + ":", y,"=",a,"x^2+",b,"x + c")
x1=float(sys.argv[1])
y1=float(sys.argv[2])
x2=float(sys.argv[3])
y2=float(sys.argv[4])
x3=float(sys.argv[5])
y3=float(sys.argv[6])
a1=x1*x1
a2=x2*x2
a3=x3*x3
b1 = x1
b2 = x2
b3 = x3
printmainfunc("1st eq:",a1,b1,y1)
printmainfunc("2nd eq:",a2,b2,y2)
printmainfunc("3rd eq:",a3,b3,y3)
newa = (a3*-1)+a1
newy =(-1*y3) + y1 
newb = (b3*-1) + b1
newa2 = (a2*-1)+a1
newy2 =(-1*y2) + y1 
newb2 = (b2*-1) + b1

printmainfunc("NEW 1st eq:",newa, newb,newy)
printmainfunc("NEW 2nd eq:", newa2,newb2,newy2)
#find a
ratio = (newb / newb2) * -1
newratioa = newa2 * ratio
newratioy = newy2 * ratio
finala = newa + newratioa
finaly = newratioy + newy
a = finaly /finala
#find b
acompound = newa * a
ycompound = newy - acompound
b = ycompound / newb
#
c = y1 - (b1 * b) - (a1 * a)
print("a=",round(a,6))
print("b=",round(b,6))
print("c=",round(c,6))
