#!/usr/bin/env python3
import sys
radical = int(sys.argv[1])
persq = [4,9,16,25,36,49,64,81,100,121,144,169,196,225,256,289,324,361,400]
for num in persq[::-1]:
    if radical % num == 0:
        print(num ** 0.5,"√",radical/num)
        break

