#!/usr/bin/env python3
'''simplifies radical'''
import sys
printI = False
works = False
radical = int(sys.argv[1])
if radical < 0:
    radical *= -1
    printI = True
persq = [4,9,16,25,36,49,64,81,100,121,144,169,196,225,256,289,324,361,400]
for num in persq[::-1]:
    if radical == num:
        print(radical ** 0.5)
        works = True
        break
    if radical % num == 0:
        if printI == True:
            print(num ** 0.5,"i√",radical/num)
        else:
            print(num ** 0.5,"√",radical/num)
        works = True
        break
if works == False:
    print('cannot be simplified')
