#!/usr/bin/env python3
print('a * b√(cx + d) + e = f')
a = float(input('a > '))
b = float(input('b > '))
c = float(input('c > '))
d = float(input('d > '))
e = float(input('e > '))
f = float(input('f > '))
iso_var_side = f-e / a
print('{}√({}x + {}) = {}'.format(b,d,e,iso_var_side))
powered_side = (iso_var_side ** b) - e
print('{}x + {} = {}'.format(c,d,powered_side))
#cx^d = side
'''NOT WORKING YET!!!
if d == 2:
   s = powered_side * -1
   #cx^2 - side = 0 
   #-b+-srb^2-4ac
   bottom = c * 2 
   top = (-4*c*s)**0.5
   top_2 = top * -1
   print(top/bottom,top_2/bottom)
'''
if d == 1:
    print(powered_side/c)
else:
    print('Ha! Have fun solving that one...')
