#!/usr/bin/env python3
print('input a, b and c seperated by spaces')
rawx = input('> ')
x = rawx.split(" ")
print('input a2, b2 and c2 seperated by spaces')
rawy = input('> ')
y = rawy.split(" ")
a1 = float(x[0])
b1 = float(x[1])
c1 = float(x[2])
a2 = float(y[0])
b2 = float(y[1])
c2 = float(y[2])
#y = a1 + b1 + c1
#y2 = a2 + b2 + c2
#a2 + b2 + c2 = a1 + b1 + c1
#a1 
a = a1 - a2
b = b1 - b2
c = c1 - c2
print("a = ",a)
print('b = ',b)
print('c = ',c)
x1 = ((-1 * b) + ((b**2) - (4* a * c)) ** 0.5)/2 * a
x2 = ((-1 * b) - ((b**2) - (4* a * c)) ** 0.5)/2 * a
y1 = (a1 * x1 * x1) + (b1 * x1) + c1
y2 = (a1 * x2 * x2) + (b1 * x2) + c1
print("(",x1,",",y1,")")
print("(",x2,",",y2,")")
