#!/usr/bin/env python3
import sys

a =float(sys.argv[1])
b = float(sys.argv[2])
c = float(sys.argv[3])
if len(sys.argv) > 4:
    print("testing")
aos = (-b)/(2*a)
print('aos:x=',str(aos))
y=(a*(aos*aos))+(b*aos)+c
print('vertex:(',str(aos),',',str(y),')')
print('y-int=(0,',str(c),')')
if a < 0:
    print('Maximum')
    print('(-∞,',str(y),']')
else: 
    print('Minimum')
    print('[',str(y),',∞)')
print("In Vertex Form")
print("--------------")
print('y=',str(a),'(x-',str(aos),')^2 + ',str(y))  
