#!/usr/bin/env python3
import sys
'''standard to vertex'''
a= int(sys.argv[1])
b = int(sys.argv[2])
c = int(sys.argv[3])
aos = (-b)/(2*a)
print('aos=',aos)
print('f(x)=a(x-h)^2+k')
p1 = aos * aos * a
p2 = (b*aos)+c
y = p1 + p2
print('f(',aos,')=',y)
print('y=',a,'(x-',aos,')^2 + ',y)
