#!/usr/bin/env python3
'''standard to vertex'''
a = -1
b = 6
c = 1
aos = (-b)/(2*a)
print('aos=',aos)
print('f(x)=a(x-h)^2+k')
p1 = aos * aos * a
p2 = (b*aos)+c
y = p1 + p2
print('f(',aos,')=',y)
print('y=',a,'(x-',aos,')^2 + ',y)
