#!/usr/bin/env python3
import sys

a =float(sys.argv[1])
b = float(sys.argv[2])
c = float(sys.argv[3])
aos = (-b)/(2*a)
print('aos=',aos)
y=(a*(aos*aos))+(b*aos)+c
print('vertex:(',aos,',',y,')')
print('y-int=(0,',c,')')
if a < 0:
    print('maximum')
    print('(-∞,',y,')')
else: 
    print('minimum')
    print('(',y,',∞)')
