#!/usr/bin/env python3
import sys

a = float(sys.argv[1])
b = float(sys.argv[2])
c = float(sys.argv[3])
new_b = b * 2 * a
new_c = ((b ** 2) * a) + c
new_a = a
print('{}x^2 + {}x + {}'.format(new_a, new_b, new_c))
