#!/usr/bin/env python3

class My_class(object):
    """The blueprint"""
    def __init__(self, name, age, money,is_cool=False):
        """what is needed for the class. jim = My_class('jim',12,100000)"""
        self.name = name
        self.age = age
        self.money = money
        self.is_cool = is_cool
        """gives the class the passed in properties"""
    
    @staticmethod 
    """static method means it doesn't need self passed in"""
    def print_hello():
        print('hello!')
    def can_drive_a_car(self, age):
        return age >= 16
  
    @classmethod
    """passes in the class, not self"""
    def tell_everything(cls):
        print(cls.name,cls.age,cls.money,cls.iscool)  
