#!/usr/bin/env python3
import curses
import time

def exitWin():
    curses.endwin()

class Brush():
    char = 'X'
    fg = ''
    bg = ''

class Artist():
    x = 1
    y = 1
    brush = None

    def poke(self,x,y):
        '''Prints a 'x' on a specific coordinate.'''
        stdscr = curses.initscr()
        curses.noecho()
        curses.start_color()
        stdscr.addstr(x,y,'x')
        stdscr.refresh()

    def move(self,direction,amount):
        '''Moves x and y of '''
        stdscr = curses.initscr()
        curses.noecho()
        if direction.startswith('d'):
            for count in range(amount):
                self.y+=1
                stdscr.addstr(self.y,self.x,'x')
        if direction.startswith('u'):
            for count in range(amount):
                self.y-=1
                stdscr.addstr(self.y,self.x,'x')
        if direction.startswith('r'):
            for count in range(amount):
                self.x+=1
                stdscr.addstr(self.y,self.x,'x')
        if direction.startswith('l'):
            for count in range(amount):
                self.x-=1
                stdscr.addstr(self.y,self.x,'x')
        stdscr.refresh()

if __name__ == '__main__':
    try:
        you = Artist()
        while True:
            direction = input("u, d, l, r > ")
            if direction == 'd':
                you.move('d',5)
                time.sleep(0.5)
            elif direction == 'r':
                you.move('r',5)
                time.sleep(0.5)
            elif direction == 'u':
                you.move('u',5)
                time.sleep(0.5)
            elif direction == 'l':
                you.move('l',5)
                time.sleep(0.5)
            else:
                time.sleep(1)
                exitWin()
    except Exception:
        exitWin()
        print(Exception)
        exit()
