#!/usr/bin/env python3

def f_iter(n):
    assert n >= 0

    a, b = [], [[1]]

    for _ in range(n):
        a, b = b, [[1] + c for c in b] + [[2] + c for c in a]

    return a
def changeToLetters(word,combos):
    sets = []
    for numset in combos:
        letterNum = 0
        while letterNum < len(word):
            myset = []
            for num in numset:	
                if num == 1:
                    myset.append(word[letterNum])
                    letterNum += 1
                else:
                    myset.append(word[letterNum] + word[letterNum+1])
                    letterNum += 2
        sets.append(myset)
    return sets

word = "bacon"
elements = ["h","he","li","be","b","c","n","o","f","ne","na","mg","al","si","p","s","cl","ar","k","ca","sc","ti","v","cr","mn","fe","co","ni","cu","zn","ga","ge","as","se","br","kr","rb","sr","y","zr","nb","mo","tc","ru","rh","pd","ag","cd","in","sn","sb","te","i","xe","cs","ba","la","ce","pr","nd","pm","sm","eu","gd","tb","dy","ho","er","tm","yb","lu","hf","ta","w","re","os","ir","pt","au","hg","tl","pb","bi","po","at","rn","fr","ra","ac","th","pa","u","np","pu","am","cm","bk","cf","es","fm","md","no","lr","rf","db","sg","bh","hs","mt","ds","rg","cn","fl","lv"]
combos = f_iter(len(word))
sets = changeToLetters(word,combos)
for eachSet in sets:
	if set(eachSet).issubset(set(elements)):
		print(eachSet)
