#!/usr/bin/env python3
import sys
import math
import itertools

def findCombos(n):
    max2s = math.floor(n/2)
    min1s = n - max2s
    sets = []
    for x in range(max2s+1):
        sets.append([x,n-(x*2)])
  
    numsets = []
    allsets = []
    for x in sets:
        numsets.append(x[0] * [2] + x[1] * [1])
    for eachset in numsets:
        if 1 in eachset and 2 in eachset:
            y = set(itertools.permutations(eachset))
            for z in y:
                allsets.append(z)
        else:
            allsets.append(tuple(eachset))
    return allsets
def changeToLetters(word,combos):
    sets = []
    for numset in combos:
        letterNum = 0
        while letterNum < len(word):
            myset = []
            for num in numset:	
                if num == 1:
                    myset.append(word[letterNum])
                    letterNum += 1
                else:
                    myset.append(word[letterNum] + word[letterNum+1])
                    letterNum += 2
        sets.append(myset)
    return sets
word = ''.join(sys.argv[1:])
elements = ["h","he","li","be","b","c","n","o","f","ne","na","mg","al","si","p","s","cl","ar","k","ca","sc","ti","v","cr","mn","fe","co","ni","cu","zn","ga","ge","as","se","br","kr","rb","sr","y","zr","nb","mo","tc","ru","rh","pd","ag","cd","in","sn","sb","te","i","xe","cs","ba","la","ce","pr","nd","pm","sm","eu","gd","tb","dy","ho","er","tm","yb","lu","hf","ta","w","re","os","ir","pt","au","hg","tl","pb","bi","po","at","rn","fr","ra","ac","th","pa","u","np","pu","am","cm","bk","cf","es","fm","md","no","lr","rf","db","sg","bh","hs","mt","ds","rg","cn","fl","lv"]
combos = findCombos(len(word))
sets = changeToLetters(word,combos)
for eachSet in sets:
	if set(eachSet).issubset(set(elements)):

