#!/usr/bin/env python3
import socket
'''
http://www.binarytides.com/python-socket-programming-tutorial/
'''
#open
#bind
#listen
#accept
#read/send
HOST = ''
PORT = 9999
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
bind_pair = (HOST, PORT)
s.bind(bind_pair)
s.listen(10)
print('SERVER LISTENING...')
#the 10 means the number of incoming connections. As stated on the tutorial:
#So by specifying 10, it means that if 10 connections are already waiting to be processed, then the 11th connection request shall be rejected.
connection, address = s.accept()
print('Connected with {} on port {}'.format(address[0],address[1]))
received_data = connection.recv(1024)
connection.sendall('THE SERVER RECEIVED THIS MESSAGE: {}'.format(received_data))
connection.close()
s.close()


