#!/usr/bin/env python3
import colors as c
import time
x = list(input(c.cl +'word > '))
time.sleep(1)
print(c.cl)
z = ['_'] * len(x)
for letter in range(len(x)):
    if x[letter] ==" ":
        z[letter] = " | "
guesses = 6
letters = []
print(' '.join(z))
while guesses > 0 and '_' in z:
    y = input('letter > ')
    if y not in letters:
        letters.append(y)
        if y in x:
            for letter in range(len(x)):
                if x[letter] == y:
                    z[letter] = y
            print(' '.join(z))
        else:
        
            guesses -= 1
            print('You have',guesses,'guesses.')
    else:
        print('already guessed that letter.')
if '_' in z:
    print('You lose. Correct word was ' +''.join(x))
else:
    print('You win!')

