#!/usr/bin/env python3
import colors as c
import time
x = list(input('word > '))
time.sleep(1)
print(c.cl)
z = ['_'] * len(x)
guesses = 6
letters = []
if ' ' in x:
    print('No spaces please.')
    exit()
print(z)
while guesses > 0 and '_' in z:
    y = input('letter > ')
    if y not in letters:
        letters.append(y)
        if y in x:
            for letter in range(len(x)):
                if x[letter] == y:
                    z[letter] = y
            print(' '.join(z))
        else:
        
            guesses -= 1
            print('You have',guesses,'guesses.')
    else:
        print('already guessed that letter.')
if '_' in z:
    print('You lose. Correct word was ' +''.join(x))
else:
    print('You win!')

